### ISSUE TITLE
Не работает пример

### ISSUE THREAD

**Issue by khusamov** [dimik/node-multi-geocoder#4]
Код:

```
var MultiGeocoder = require('multi-geocoder'),
    geocoder = new MultiGeocoder({ provider: 'yandex-cache', coordorder: 'latlong' });

geocoder.geocode(['Moscow', 'New York', 'Paris', 'London'])
.then(function (res) {
    console.log(res);
});
```

Текст ошибки:

```
/home/ubuntu/workspace/node_modules/multi-geocoder/lib/providers/yandex/geojson-view.js:17
            throw new Error('GeoObject Not Found');
            ^

Error: GeoObject Not Found
    at module.exports.inherit.toGeoJSON (multi-geocoder/lib/providers/yandex/geojson-view.js:17:19)
    at module.exports.inherit.process (multi-geocoder/lib/providers/yandex/geocode-provider.js:12:21)
    at .<anonymous> (multi-geocoder/lib/providers/base-geocode-provider.js:38:24)
    at Request.callback (superagent/lib/node/index.js:591:12)
    at superagent/lib/node/index.js:766:18
    at Stream.<anonymous> (superagent/lib/node/parsers/json.js:16:7)
    at emitNone (events.js:86:13)
    at Stream.emit (events.js:185:7)
    at Unzip.<anonymous> (superagent/lib/node/utils.js:108:12)
    at emitNone (events.js:91:20)
```

**Comment by khusamov** [comment]
А вот так ошибки нет
```
...
geocoder.geocode(['Moscow'])
...
```

**Comment by khusamov** [comment]
Похоже на Нью Йорке проблемы.

Ответ `.response.GeoObjectCollection` содержит

```
{ metaDataProperty: 
   { GeocoderResponseMetaData: 
      { request: 'New York',
        found: '0',
        results: '1',
        boundedBy: [Object] } },
  featureMember: [] }
```

В итоге переменная `.response.GeoObjectCollection.featureMember[0].GeoObject` не определена

**Comment by dimik** [comment]
Соглласно документации на геокодер, для поиска вне РУБКи нужно передавать ключ

https://tech.yandex.ru/maps/doc/geocoder/desc/concepts/input_params-docpage/

> Ограничение. Если параметр key не передан, то поиск доступен только для следующих стран: Россия, Украина, Беларусь, Казахстан, Грузия, Абхазия, Южная Осетия, Армения, Азербайджан, Молдавия, Туркмения, Таджикистан, Узбекистан, Киргизия и Турция.

**Comment by khusamov** [comment]
Проблема осложняется тем, что вышеуказанная ошибка не отлавливается в catch промиса. Она все рушит в итоге. Если бы ненайденые адреса попадали в catch и errors, то это было бы приемлимо. А сейчас как блокировать это исключение?

**Comment by dimik** [comment]
Исправил v0.1.6
