### ISSUE TITLE
Количество загруженных адресов не совпадает с количеством результатов

### ISSUE THREAD

**Issue by khusamov** [dimik/node-multi-geocoder#5]
Я загрузил адресов 1024, а результатов (features.length) получил 1011

В итоге не известно какие адреса пропущены.

При каких обстаятельствах ваш скрипт может пропускать адрес???

**Comment by dimik** [comment]
Может пропускать, если они не найдены.
Информация о не найденных объектах (Запрос, индекс и причина ошибки) возвращается в поле [errors](https://github.com/dimik/node-multi-geocoder/blob/master/lib/multi-geocoder.js#L47)

**Comment by khusamov** [comment]
А как мне сопоставить найденные адреса с моим исходным списком объектов? Я их сопоставлял по index. А теперь, когда неизвестно какие были отброшены возможно будет смещение.

**Comment by dimik** [comment]
Там есть индекс в исходном массиве, по нему и сопоставьте
