### ISSUE TITLE
Как получить больше 1го результата на 1 запрос?

### ISSUE THREAD

**Issue by alexsorokoletov** [dimik/node-multi-geocoder#6]
Например, Минск, Калинина 1. Яндекс отвечает улица Калинина 1 и переулок Калинина 1.
`toGeoJSON` работает только с первым результатом.

Можно конечно просто делать запросы в Яндекс, но очень нравится yandex-cache провайдер

**Comment by dimik** [comment]
Видимо убрать [results: 1](https://github.com/dimik/node-multi-geocoder/blob/master/lib/providers/yandex/geocode-provider.js#L19) и формировать во [view](https://github.com/dimik/node-multi-geocoder/blob/master/lib/providers/yandex/geojson-view.js#L30) FeatureCollection

**Comment by alexsorokoletov** [comment]
@dimik это как-то без модификации вашего кода можно сделать? Или форк это единственный способ?

Спасибо за ответ

**Comment by dimik** [comment]
Должно быть можно.
В метод [geocode](https://github.com/dimik/node-multi-geocoder/blob/master/lib/multi-geocoder.js#L20) можно передать опции (перекрыть results)

Через [getProvider](https://github.com/dimik/node-multi-geocoder/blob/master/lib/multi-geocoder.js#L12) получить провайдер и перекрыть ему метод [process](https://github.com/dimik/node-multi-geocoder/blob/master/lib/providers/yandex/geocode-provider.js#L9) своей реализацией, в которой возвращать то что нужно

**Comment by alexsorokoletov** [comment]
Спасибо за подсказку.
Пришлось сделать следующие движения:
1. передать как опции { results: 2}
2. перекрыть process 
3. в обработке результатов вместо объекта в промис `res.result.features[0]` приходит массив объектов. 

Было бы прекрасно в следующей версии уметь получать несколько результатов без магии :)

Еще раз спасибо за помощь.

**Comment by dimik** [comment]
Это не магия, process это спец-метод для перекрытия, в базовом классе провайдера он просто [возвращает](https://github.com/dimik/node-multi-geocoder/blob/master/lib/providers/base-geocode-provider.js#L50) результат как есть.

Возвращать вложенные коллекции не получится, т.к. формат [GeoJSON](http://geojson.org/geojson-spec.html#feature-collection-objects) не поддерживает такой синтаксис

**Comment by alexsorokoletov** [comment]
Вы правы, не подумал о спецификации GeoJSON 

Alex
